clearvars

close all

%%%THIS SCRIPT USES THE NUMBER OF FOCI PER WELL AS DETERMINED FROM
%%%ffuAnalysisv7_1_SC_final AND NORMALIZES TO THE NO PLASMA INFECTION
%%%CONTROL, THEN PREFORMS FITS AND ANALYSIS.

%By Alex Sigal, 2021

%SECTIONS AND ORDER TO COMPILE:

%1. singleExp (SET TO 1 TO RUN). Noramalizes by no plasma infection control
%and stores in combined folder. Requires resultsFFU.xlsx generated by ffuAnalysisv7_1_SC_final to be in the
%directory.

%2. combineAllData (SET TO 1 TO RUN). Combines experiments and does fitting
%to sigmoidal function.

%3. Check for normality of all participant data per dilution using findGoF (SET TO 1 TO RUN)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
singleExp =2; %%%%run this first on each exp for the data file to transfer to combined exp
exp = 1:10; %%% experiment can be vector, as for loop
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
combineAllData =1;
numberExperiments = 10;
experimentsSet1 = 1:3; %exp 1,2,3 on same PIDS
experimentsSet2 = 4:7; %exp 4,5,6,7 on same PIDS
experimentsSet3 = 8:10; %exp 8,9,10 on same PIDS
numberSamplesSet1 =8; %including PUI
numberSamplesSet2 =10; %including PUI
numberSamplesSet3 =10; %including PUI
numberSamplesSet1ExclCon =6; 
numberSamplesSet2ExclCon =8; 
numberSamplesSet3ExclCon =8; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
findGoF =0;
useWt =0; %%%Choses whether to graph wt (early variant) or mt (501Y.V2 virus). default is mt
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%WHERE FILES FROM SINGLE EXP ANALYSIS STORED FOR COMBINING
dirCombined ='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\combResultsExp8to12';


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Single experiment
if singleExp ==1
    
    %%%Locations of files. dir is directory for infection with early variant, 
%%%dirMatchingPlate is directory for infection with the 501Y.V2 variant for the same experiment 
        for experiment = exp
                
                if      experiment == 1

                        %exp 8 = 1 in matlab order 

                        dir ='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\8thNeut1313_28_01_2021';
                        dirMatchingPlate = 'C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\8thNeut6518_28_01_2021';

                elseif      experiment == 2

                        %exp 9a = 2 in matlab order 

                        dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\9thNeut1313p1_02_02_21';
                        dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\9thNeut6518p1_02_02_21';

                elseif      experiment == 3

                        %exp 9b = 3 in matlab order 

                        dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\9thNeut1313p2_02_02_21';
                        dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\9thNeut6518p2_02_02_21';

                elseif      experiment == 4

                        %exp10a = 4 in matlab order 

                        dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut1313p1_06_02_21';
                        dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut6518p1_06_02_21';

                elseif      experiment == 5

                        %exp10b = 5 in matlab order 

                        dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut1313p2_06_02_21';
                        dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut6518p2_06_02_21';

                elseif      experiment == 6

                        %exp10c = 6 in matlab order 

                        dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut1313p3_06_02_21';
                        dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\10thNeut6518p3_06_02_21';

                elseif      experiment == 7

                        %exp11 = 7 in matlab order 

                    dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\11thNeut1313_10_02_21';
                    dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\11thNeut6518_10_02_21';


                elseif      experiment == 8

                    %exp12a = 8 in matlab order 

                    dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut1313p1_13_02_21';
                    dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut6518p1_13_02_21';

                elseif      experiment == 9

                    %exp12a = 8 in matlab order 

                    dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut1313p2_13_02_21';
                    dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut6518p2_13_02_21';

                elseif      experiment == 10

                    %exp12a = 8 in matlab order 

                    dir='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut1313p3_13_02_21';
                    dirMatchingPlate='C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\12thNeut6518p3_13_02_21';
                end

       
            nameFig1 ='1st Wave Norm No Plasma';

            nameFig2 ='501Yv2 Norm No Plasma';

            
            %% Import data from spreadsheet
            % Script for importing data from the following spreadsheet:
            %
            %    Workbook: C:\SAforBackup\papersInProgress\abEscape\allSandileNeuts\501v2secondNeut01_01_21\501Yv2secondNeutVeroRabbit01_01_21\2xScan\resultsFFU.xlsx
            %    Worksheet: Sheet1
            %
            % Auto-generated by MATLAB on 03-Jan-2021 13:32:11

            opts = spreadsheetImportOptions("NumVariables", 12);

            % Specify sheet and range
            opts.Sheet = "Sheet1";
            opts.DataRange = "A1:L8"; %%%change depending on what part of the plate used. must match numVariables above - do import and generate script




            % Specify column names and types
            opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
            opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

            % Import the data
            resultsFFU = readtable([dir '\resultsFFU.xlsx'], opts, "UseExcel", false);

            %% Clear temporary variables
            clear opts

            %%%converts to matrix
            resultsFFU = resultsFFU{:,:}; %%%%half plate done, vertically


                    %%%IMPORT MATCHING 501Y.V2 infection data

                    %% Setup the Import Options and import the data

            opts = spreadsheetImportOptions("NumVariables", 12);

            % Specify sheet and range
            opts.Sheet = "Sheet1";
            opts.DataRange = "A1:L8"; %%%change depending on what part of the plate used. must match numVariables above - do import and generate script

            % Specify column names and types
            opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
            opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

            % Import the data

            resultsFFUmatchTable = readtable([dirMatchingPlate '\resultsFFU.xlsx'], opts, "UseExcel", false);

            resultsFFUmatch = table2array(resultsFFUmatchTable);


            %% Clear temporary variables
            clear opts

            %%%%IMPORTANT
            %%%%for exp 10 (exp 4,5,6 in matlab order), PUI and No plasma switched.
            %%%%for exp 11, no plasma control is column 11
            %background signal (no infection) is always column 12, all rows

            backgroundSigWt = mean(resultsFFU(1:8, 12));
            backgroundSigMt = mean(resultsFFUmatch(1:8, 12));



            if      experiment == 1 || experiment == 2 || experiment == 3

                backgroundSigWt = mean(resultsFFU(1:8, 12));
                backgroundSigMt = mean(resultsFFUmatch(1:8, 12));

                meanNoPlasmaWt = mean(resultsFFU(2:8, 10));

                meanNoPlasmaMt = mean(resultsFFUmatch(2:8, 10));

                matrixWt = (resultsFFU(2:8, 2:9)-backgroundSigWt)./meanNoPlasmaWt; 

                matrixMt = (resultsFFUmatch(2:8, 2:9)-backgroundSigMt)./meanNoPlasmaMt;



                %%%here PUI column is after no plasma control, need to remove it and
                %%%place it in consecutive order
            elseif    experiment == 4 || experiment == 5 || experiment == 6

                meanNoPlasmaWt = mean(resultsFFU(2:8, 10));

                meanNoPlasmaMt = mean(resultsFFUmatch(2:8, 10));

                 puiColumnWt = resultsFFU(2:8, 11)./meanNoPlasmaWt; 

                 puiColumnMt = resultsFFUmatch(2:8, 11)./meanNoPlasmaMt;

                 matrixWt = (resultsFFU(2:8, 1:9)--backgroundSigWt)./meanNoPlasmaWt; 

                matrixMt = (resultsFFUmatch(2:8, 1:9)-backgroundSigMt)./meanNoPlasmaMt;

                %%%add PUI column

                 matrixWt = [matrixWt, puiColumnWt]; %%%PUI now column 10

                 matrixMt = [matrixMt, puiColumnMt];  %%%PUI now column 10

            %%%here PUI column is before no plasma control
            elseif    experiment == 7 || experiment == 8 || experiment == 9 || experiment == 10

                meanNoPlasmaWt = mean(resultsFFU(2:8, 11));

                meanNoPlasmaMt = mean(resultsFFUmatch(2:8, 11));


                 matrixWt = (resultsFFU(2:8, 1:10)--backgroundSigWt)./meanNoPlasmaWt; 

                matrixMt = (resultsFFUmatch(2:8, 1:10)--backgroundSigMt)./meanNoPlasmaMt;

                %
             end

            xAxis = 1:7;
            
            
%%%WT FIGURE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            % Create figure
            figure1 = figure;

            axes1 = axes('Parent',figure1);

             hold(axes1,'on');

            xlabel("Dilution")
            ylabel("FFU/FFU no plasma")

            title(nameFig1,'FontSize',14,'FontWeight','bold');

            plot1 = plot(xAxis, matrixWt);%, 'LineStyle', '-', 'LineWidth', 1, 'Color', [0 0 0]);

             set(gca,'XTick',(1:7));

            set(gca,'XTickLabel',{'1:25','1:50', '1:100','1:200','1:400', '1:800', '1:1600'});

            set(gca,'YTick',(0:0.5:1.5));

            set(gca,'YTickLabel',{'0','0.5','1', '1.5'});

            set(gca,'ylim',[0 1.5]);

                    if experiment == 1 || experiment == 2 || experiment == 3



                    set(plot1(1),'DisplayName','A2051');
                    set(plot1(2),'DisplayName','039-02-0017');
                    set(plot1(3),'DisplayName','039-02-0014');
                    set(plot1(4),'DisplayName','039-13-0013');
                     set(plot1(5),'DisplayName','039-13-0015');
                     set(plot1(6),'DisplayName','039-13-0033');
                     set(plot1(7),'DisplayName','039-13-0062');
                    set(plot1(8),'DisplayName','PUI');
            %                 set(plot1(7),'DisplayName','Control pool');

                    set(plot1(8),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot1(1),'Color',[0 0 0], 'LineWidth', 2);

                    elseif experiment == 4 || experiment == 5 || experiment == 6 || experiment == 7


                        set(plot1(1),'DisplayName','A2051');
                    set(plot1(2),'DisplayName','039-13-0037');
                    set(plot1(3),'DisplayName','039-13-0038');
                    set(plot1(4),'DisplayName','039-13-0060');
                     set(plot1(5),'DisplayName','039-13-0103');
                     set(plot1(6),'DisplayName','039-02-0030');
                     set(plot1(7),'DisplayName','039-02-0031');
                     set(plot1(8),'DisplayName','039-02-0033');
                     set(plot1(9),'DisplayName','039-02-0036');
                    set(plot1(10),'DisplayName','PUI');

                     set(plot1(10),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot1(1),'Color',[0 0 0], 'LineWidth', 2);

                    set(plot1(2),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(3),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(4),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(5),'Color',[0 0.5 0], 'LineWidth', 1);
                    set(plot1(6),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(7),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(8),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(9),'Color',[0 0 0.5], 'LineWidth', 1);
                    
                    elseif experiment == 8 || experiment == 9 || experiment == 10 
                        
                        set(plot1(1),'DisplayName','A2051');
                    set(plot1(2),'DisplayName','039-02-0005');
                    set(plot1(3),'DisplayName','039-02-0011');
                    set(plot1(4),'DisplayName','039-02-0013');
                     set(plot1(5),'DisplayName','039-13-0018');
                     set(plot1(6),'DisplayName','039-02-0032');
                     set(plot1(7),'DisplayName','039-02-0034');
                     set(plot1(8),'DisplayName','039-02-0037');
                     set(plot1(9),'DisplayName','039-09-0001');
                    set(plot1(10),'DisplayName','PUI');

                     set(plot1(10),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot1(1),'Color',[0 0 0], 'LineWidth', 2);

                    set(plot1(2),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(3),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(4),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot1(5),'Color',[0 0.5 0], 'LineWidth', 1);
                    set(plot1(6),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(7),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(8),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot1(9),'Color',[0 0 0.5], 'LineWidth', 1);
                        
                        


                    end

            legend(axes1,'show');


            cd(dir)           
            saveas(gcf,nameFig1,'jpg');
            
            
            
%%%MT FIGURE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%            


            % Create figure
            figure2 = figure;

            axes2 = axes('Parent',figure2);
            hold(axes2,'on');
            xlabel("Dilution")
            ylabel("FFU/FFU no plasma")

            title(nameFig2,'FontSize',14,'FontWeight','bold');

            plot2 = plot(xAxis, matrixMt);%, 'LineStyle', '-', 'LineWidth', 1, 'Color', [0 0 0]);

            set(gca,'XTick',(1:7));

            set(gca,'XTickLabel',{'1:25','1:50', '1:100','1:200','1:400', '1:800', '1:1600'});

            set(gca,'YTick',(0:0.5:1.5));

            set(gca,'YTickLabel',{'0','0.5','1', '1.5'});

            set(gca,'ylim',[0 1.5]);

                  if experiment == 1 || experiment == 2 || experiment == 3 




                    set(plot2(1),'DisplayName','A2051');
                    set(plot2(2),'DisplayName','039-02-0017');
                    set(plot2(3),'DisplayName','039-02-0014');
                    set(plot2(4),'DisplayName','039-13-0013');
                     set(plot2(5),'DisplayName','039-13-0015');
                     set(plot2(6),'DisplayName','039-13-0033');
                     set(plot2(7),'DisplayName','039-13-0062');
                    set(plot2(8),'DisplayName','PUI');
            %                 set(plot1(7),'DisplayName','Control pool');

                    set(plot2(8),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot2(1),'Color',[0 0 0], 'LineWidth', 2);

                    elseif experiment == 4 || experiment == 5 || experiment == 6 || experiment == 7



                        set(plot2(1),'DisplayName','A2051');
                    set(plot2(2),'DisplayName','039-13-0037');
                    set(plot2(3),'DisplayName','039-13-0038');
                    set(plot2(4),'DisplayName','039-13-0060');
                     set(plot2(5),'DisplayName','039-13-0103');
                     set(plot2(6),'DisplayName','039-02-0030');
                     set(plot2(7),'DisplayName','039-02-0031');
                     set(plot2(8),'DisplayName','039-02-0033');
                     set(plot2(9),'DisplayName','039-02-0036');
                    set(plot2(10),'DisplayName','PUI');

                     set(plot2(10),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot2(1),'Color',[0 0 0], 'LineWidth', 2);

                    set(plot2(2),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(3),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(4),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(5),'Color',[0 0.5 0], 'LineWidth', 1);
                    set(plot2(6),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(7),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(8),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(9),'Color',[0 0 0.5], 'LineWidth', 1);
                    
                    elseif experiment == 8 || experiment == 9 || experiment == 10 
                        
                        set(plot2(1),'DisplayName','A2051');
                    set(plot2(2),'DisplayName','039-02-0005');
                    set(plot2(3),'DisplayName','039-02-0011');
                    set(plot2(4),'DisplayName','039-02-0013');
                     set(plot2(5),'DisplayName','039-13-0018');
                     set(plot2(6),'DisplayName','039-02-0032');
                     set(plot2(7),'DisplayName','039-02-0034');
                     set(plot2(8),'DisplayName','039-02-0037');
                     set(plot2(9),'DisplayName','039-09-0001');
                    set(plot2(10),'DisplayName','PUI');

                     set(plot2(10),'Color',[0.5 0.5 0.5], 'LineWidth', 2);

                    set(plot2(1),'Color',[0 0 0], 'LineWidth', 2);

                    set(plot2(2),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(3),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(4),'Color',[0.5 0 0], 'LineWidth', 1);
                    set(plot2(5),'Color',[0 0.5 0], 'LineWidth', 1);
                    set(plot2(6),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(7),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(8),'Color',[0 0 0.5], 'LineWidth', 1);
                    set(plot2(9),'Color',[0 0 0.5], 'LineWidth', 1);
                        


                  end

            legend(axes2,'show');

            saveas(gcf,nameFig2,'jpg');      

            cd(dirCombined)

            nameDataFile =  (['resultsFFUexp' num2str(experiment)]);

            save(nameDataFile, 'matrixWt', 'matrixMt');

        end    
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%Combine data
if combineAllData ==1
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%EXTRACT AND COMBINE DATA
    
    %%%%%NOTE AS DATA NORMALIZED BY NO PLASMA, THE NO PLASMA COLUMN DOES NOT APPEAR
     
 cd(dirCombined)
 combMatrixWt1 =zeros(7,numberSamplesSet1,numel(experimentsSet1));
 combMatrixMt1 =zeros(7,numberSamplesSet1,numel(experimentsSet1));
 
 combMatrixWt2 =zeros(7,numberSamplesSet2,numel(experimentsSet2));
 combMatrixMt2 =zeros(7,numberSamplesSet2,numel(experimentsSet2));
 
 combMatrixWt3 =zeros(7,numberSamplesSet3,numel(experimentsSet3));
 combMatrixMt3 =zeros(7,numberSamplesSet3,numel(experimentsSet3));
 
 %%%to combine A2051 and PUI across experiment sets
 
 a2051Wt = zeros(7,1, numberExperiments);
 a2051Mt = zeros(7,1, numberExperiments);
 
 puiWt = zeros(7,1, numberExperiments);
 puiMt = zeros(7,1, numberExperiments);
 
 
 
 %%%%set 1: exp 1,2, 3 with same PIDS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 for index=1:numel(experimentsSet1)
     
     expNum = experimentsSet1(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
           combMatrixWt1(:,:,index) =matrixWt;
           
           a2051Wt(:,:,index) = matrixWt(:,1); %%%first col is A2051
           
           puiWt(:,:,index) = matrixWt(:,8); %%%last col is PUI
           
           combMatrixMt1(:,:,index) =matrixMt;
           
           a2051Mt(:,:,index) = matrixMt(:,1);
           
           puiMt(:,:,index) = matrixMt(:,8);
           
     
 end
 
 meanWt1 = mean(combMatrixWt1, 3);
 
 meanMt1 = mean(combMatrixMt1, 3);
 
 meanFracNeutWt1 = mean(1-combMatrixWt1, 3);

meanFracNeutMt1 = mean(1-combMatrixMt1, 3);

%Take out negative values

meanFracNeutNoZeroWt1 = meanFracNeutWt1;

meanFracNeutNoZeroWt1(find(meanFracNeutNoZeroWt1<0))=0;

meanFracNeutNoZeroMt1 = meanFracNeutMt1;

meanFracNeutNoZeroMt1(find(meanFracNeutNoZeroMt1<0))=0;
 
 stdWt1 = std(combMatrixWt1,0, 3)./sqrt(numel(experimentsSet1));
 
 stdMt1 = std(combMatrixMt1,0, 3)./sqrt(numel(experimentsSet1));
 
 stdFracNeutWt1 = std(1-combMatrixWt1,0, 3)./sqrt(numel(experimentsSet1));

stdFracNeutMt1 = std(1-combMatrixMt1,0, 3)./sqrt(numel(experimentsSet1));
 
 %seperate A2051 data - will be combined across experiments
 
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%set 2: exp 4,5,6,7 with same PIDS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  for index=1:numel(experimentsSet2)
     
     expNum = experimentsSet2(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
           combMatrixWt2(:,:,index) =matrixWt;
           
           %%%+numel(experimentsSet1) adds it to the a2051 and pui from set
           %%%1
           
           a2051Wt(:,:,index+numel(experimentsSet1)) = matrixWt(:,1); %%%first col is A2051
           
           puiWt(:,:,index+numel(experimentsSet1)) = matrixWt(:,10); %%%last col is PUI
           
           combMatrixMt2(:,:,index) =matrixMt;
           
           a2051Mt(:,:,index+numel(experimentsSet1)) = matrixMt(:,1);
           
           puiMt(:,:,index+numel(experimentsSet1)) = matrixMt(:,10);
           
     
 end
 
 meanWt2 = mean(combMatrixWt2, 3);
 
 meanMt2 = mean(combMatrixMt2, 3);
 
meanFracNeutWt2 = mean(1-combMatrixWt2, 3);

meanFracNeutMt2 = mean(1-combMatrixMt2, 3);

%Take out negative values

meanFracNeutNoZeroWt2 = meanFracNeutWt2;

meanFracNeutNoZeroWt2(find(meanFracNeutNoZeroWt2<0))=0;

meanFracNeutNoZeroMt2 = meanFracNeutMt2;

meanFracNeutNoZeroMt2(find(meanFracNeutNoZeroMt2<0))=0;


 stdWt2 = std(combMatrixWt2,0, 3)./sqrt(numel(experimentsSet2));
 
 stdMt2 = std(combMatrixMt2,0, 3)./sqrt(numel(experimentsSet2));
 
 stdFracNeutWt2 = std(1-combMatrixWt2,0, 3)./sqrt(numel(experimentsSet2));

stdFracNeutMt2 = std(1-combMatrixMt2,0, 3)./sqrt(numel(experimentsSet2));

%%%THIRD SET
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%set 3: exp 8,9,10 with same PIDS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  for index=1:numel(experimentsSet3)
     
     expNum = experimentsSet3(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
           combMatrixWt3(:,:,index) =matrixWt;
           
           %%%+numel(experimentsSet1) adds it to the a2051 and pui from set
           %%%1
           
           a2051Wt(:,:,index+numel(experimentsSet1)+numel(experimentsSet2)) = matrixWt(:,1); %%%first col is A2051
           
           puiWt(:,:,index+numel(experimentsSet1)+numel(experimentsSet2)) = matrixWt(:,10); %%%last col is PUI
           
           combMatrixMt3(:,:,index) =matrixMt;
           
           a2051Mt(:,:,index+numel(experimentsSet1)+numel(experimentsSet2)) = matrixMt(:,1);
           
           puiMt(:,:,index+numel(experimentsSet1)+numel(experimentsSet2)) = matrixMt(:,10);
           
     
 end
 
 meanWt3 = mean(combMatrixWt3, 3);
 
 meanMt3 = mean(combMatrixMt3, 3);
 
meanFracNeutWt3 = mean(1-combMatrixWt3, 3);

meanFracNeutMt3 = mean(1-combMatrixMt3, 3);

%Take out negative values

meanFracNeutNoZeroWt3 = meanFracNeutWt3;

meanFracNeutNoZeroWt3(find(meanFracNeutNoZeroWt3<0))=0;

meanFracNeutNoZeroMt3 = meanFracNeutMt3;

meanFracNeutNoZeroMt3(find(meanFracNeutNoZeroMt3<0))=0;


 stdWt3 = std(combMatrixWt3,0, 3)./sqrt(numel(experimentsSet3));
 
 stdMt3 = std(combMatrixMt3,0, 3)./sqrt(numel(experimentsSet3));
 
 stdFracNeutWt3 = std(1-combMatrixWt3,0, 3)./sqrt(numel(experimentsSet3));

stdFracNeutMt3 = std(1-combMatrixMt3,0, 3)./sqrt(numel(experimentsSet3));

%% COMBINE ALL DATASETS, TAKING OUT A2051 AND PUI
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
meanWt1trim = meanWt1(:,2:7);
meanWt2trim = meanWt2(:,2:9);
meanWt3trim = meanWt3(:,2:9);

meanMt1trim = meanMt1(:,2:7);
meanMt2trim = meanMt2(:,2:9);
meanMt3trim = meanMt3(:,2:9);

stdWt1trim = stdWt1(:,2:7);
stdWt2trim = stdWt2(:,2:9);
stdWt3trim = stdWt3(:,2:9);

stdMt1trim = stdMt1(:,2:7);
stdMt2trim = stdMt2(:,2:9);
stdMt3trim = stdMt3(:,2:9);

meanWtCombinedSet = [meanWt1trim, meanWt2trim, meanWt3trim];
meanMtCombinedSet = [meanMt1trim, meanMt2trim, meanMt3trim];

stdWtCombinedSet = [stdWt1trim, stdWt2trim, stdWt3trim];
stdMtCombinedSet = [stdMt1trim, stdMt2trim, stdMt3trim];

meanFracNeutNoZeroWt1trim = meanFracNeutNoZeroWt1(:,2:7);
meanFracNeutNoZeroWt2trim = meanFracNeutNoZeroWt2(:,2:9);
meanFracNeutNoZeroWt3trim = meanFracNeutNoZeroWt3(:,2:9);

meanFracNeutNoZeroMt1trim = meanFracNeutNoZeroMt1(:,2:7);
meanFracNeutNoZeroMt2trim = meanFracNeutNoZeroMt2(:,2:9);
meanFracNeutNoZeroMt3trim = meanFracNeutNoZeroMt3(:,2:9);

stdFracNeutWt1trim = stdFracNeutWt1(:,2:7);
stdFracNeutWt2trim = stdFracNeutWt2(:,2:9);
stdFracNeutWt3trim = stdFracNeutWt3(:,2:9);

stdFracNeutMt1trim = stdFracNeutMt1(:,2:7);
stdFracNeutMt2trim = stdFracNeutMt2(:,2:9);
stdFracNeutMt3trim = stdFracNeutMt3(:,2:9);

meanFracWtCombinedSet = [meanFracNeutNoZeroWt1trim, meanFracNeutNoZeroWt2trim, meanFracNeutNoZeroWt3trim];
meanFracMtCombinedSet = [meanFracNeutNoZeroMt1trim, meanFracNeutNoZeroMt2trim, meanFracNeutNoZeroMt3trim];

stdFracWtCombinedSet = [stdFracNeutWt1trim,stdFracNeutWt2trim,stdFracNeutWt3trim];
stdFracMtCombinedSet = [stdFracNeutMt1trim,stdFracNeutMt2trim,stdFracNeutMt3trim];



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% take means of multiple participants: first wave vs second wave plasmas



meanWtCombinedSelFWpl = meanWtCombinedSet(:,[1:9, 15:18]);
meanMtCombinedSelFWpl = meanMtCombinedSet(:,[1:9, 15:18]);

meanWtCombinedSelSWpl = meanWtCombinedSet(:,[11:13, 19,20,22]);
meanMtCombinedSelSWpl = meanMtCombinedSet(:,[11:13, 19,20,22]);

stdWtCombinedSelFWpl = stdWtCombinedSet(:,[1:9, 15:18]); 
stdMtCombinedSelFWpl = stdMtCombinedSet(:,[1:9, 15:18]); 

stdWtCombinedSelSWpl = stdWtCombinedSet(:,[11:13, 19,20,22]); 
stdMtCombinedSelSWpl = stdMtCombinedSet(:,[11:13, 19,20,22]); 


meanFracWtCombinedSelFWpl= meanFracWtCombinedSet(:,[1:9, 15:18]); 
meanFracMtCombinedSelFWpl= meanFracMtCombinedSet(:,[1:9, 15:18]); 

meanFracWtCombinedSelSWpl= meanFracWtCombinedSet(:,[11:13, 19,20,22]);
meanFracMtCombinedSelSWpl= meanFracMtCombinedSet(:,[11:13, 19,20,22]); 

stdFracWtCombinedSelFWpl = stdFracWtCombinedSet(:,[1:9, 15:18]);
stdFracMtCombinedSelFWpl = stdFracMtCombinedSet(:,[1:9, 15:18]);

stdFracWtCombinedSelSWpl = stdFracWtCombinedSet(:,[11:13, 19,20,22]);
stdFracMtCombinedSelSWpl = stdFracMtCombinedSet(:,[11:13, 19,20,22]);


%%%%%mean and std of combined sets

meanAllWtFWpl = mean(meanWtCombinedSelFWpl,2);
meanAllMtFWpl = mean(meanMtCombinedSelFWpl,2);
meanAllWtSWpl = mean(meanWtCombinedSelSWpl,2);
meanAllMtSWpl = mean(meanMtCombinedSelSWpl,2);

stdAllWtFWpl = std(meanWtCombinedSelFWpl,0,2);%./(numel(meanWtCombinedSelFWpl)*3);% se, number of experiments is number samples x3 repeats each
stdAllMtFWpl = std(meanMtCombinedSelFWpl,0,2);%./(numel(meanMtCombinedSelFWpl)*3);
stdAllWtSWpl = std(meanWtCombinedSelSWpl,0,2);%./(numel(meanWtCombinedSelSWpl)*3);
stdAllMtSWpl = std(meanMtCombinedSelSWpl,0,2);%./(numel(meanMtCombinedSelSWpl)*3);

meanFracAllWtFWpl = mean(meanFracWtCombinedSelFWpl,2);
meanFracAllMtFWpl = mean(meanFracMtCombinedSelFWpl,2);
meanFracAllWtSWpl = mean(meanFracWtCombinedSelSWpl,2);
meanFracAllMtSWpl = mean(meanFracMtCombinedSelSWpl,2);

stdFracAllWtFWpl = std(meanFracWtCombinedSelFWpl,0,2);%./(numel(meanWtCombinedSelFWpl)*3);
stdFracAllMtFWpl = std(meanFracMtCombinedSelFWpl,0,2);%./(numel(meanMtCombinedSelFWpl)*3);
stdFracAllWtSWpl = std(meanFracWtCombinedSelSWpl,0,2);%./(numel(meanWtCombinedSelSWpl)*3);
stdFracAllMtSWpl = std(meanFracMtCombinedSelSWpl,0,2);%./(numel(meanMtCombinedSelSWpl)*3);



 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 

 %%%mean and std across all A2051
 meanA2051Wt = mean(a2051Wt, 3);
 meanFracNeutA2051Wt =  mean(1-a2051Wt, 3);
 meanFracNeutA2051NoZeroWt= meanFracNeutA2051Wt;
 meanFracNeutA2051NoZeroWt(find(meanFracNeutA2051NoZeroWt<0))=0;
 
 stdA2051Wt = std(a2051Wt,0, 3)./sqrt(numel(1:numberExperiments));
 stdFracNeutA2051Wt = std(1-a2051Wt,0, 3)./sqrt(numel(1:numberExperiments));
 
 meanA2051Mt = mean(a2051Mt, 3);
 meanFracNeutA2051Mt =  mean(1-a2051Mt, 3);
 meanFracNeutA2051NoZeroMt= meanFracNeutA2051Mt;
 meanFracNeutA2051NoZeroMt(find(meanFracNeutA2051NoZeroMt<0))=0;
 
 
 stdA2051Mt = std(a2051Mt,0, 3)./sqrt(numel(1:numberExperiments));
 stdFracNeutA2051Mt = std(1-a2051Mt,0, 3)./sqrt(numel(1:numberExperiments));
 
 
 
  %%%mean and std across all PUI
 meanPuiWt = mean(puiWt, 3);
 meanFracNeutPuiWt =  mean(1-puiWt, 3);
 meanFracNeutPuiNoZeroWt= meanFracNeutPuiWt;
 meanFracNeutPuiNoZeroWt(find(meanFracNeutPuiNoZeroWt<0))=0;
 

 stdPuiWt = std(puiWt,0, 3)./sqrt(numel(1:numberExperiments));
 stdFracNeutPuiWt = std(1-puiWt,0, 3)./sqrt(numel(1:numberExperiments));
 
 meanPuiMt = mean(puiMt, 3);
 meanFracNeutPuiMt =  mean(1-puiMt, 3);
 meanFracNeutPuiNoZeroMt= meanFracNeutPuiMt;
 meanFracNeutPuiNoZeroMt(find(meanFracNeutPuiNoZeroMt<0))=0;
 
 stdPuiMt = std(puiMt,0, 3)./sqrt(numel(1:numberExperiments));
 stdFracNeutPuiMt = std(1-puiMt,0, 3)./sqrt(numel(1:numberExperiments));
 
 
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%GRAPH AND FIT
 

xAxis = [0.04; 0.02; 0.01; 0.01/2; 0.01/4; 0.01/8; 0.01/16];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%ORDER OF SAMPLES IN PLOT1 AND PLOT2
%SET 1
%  %POINTS
% plot1(1),'DisplayName','039-02-0017'
% plot1(2),'DisplayName','039-02-0014'
% plot1(3),'DisplayName','039-13-0013'
% plot1(4),'DisplayName','039-13-0015'
% plot1(5),'DisplayName','039-13-0033'
% plot1(6),'DisplayName','039-13-0062'       
% plot1(7),'DisplayName','039-13-0037'
% plot1(8),'DisplayName','039-13-0038'
% plot1(9),'DisplayName','039-13-0060'
% plot1(10),'DisplayName','039-13-0103'
% plot1(11),'DisplayName','039-02-0030'
% plot1(12),'DisplayName','039-02-0031'
% plot1(13),'DisplayName','039-02-0033'
% plot1(14),'DisplayName','039-02-0036' 
% plot1(15),'DisplayName','039-02-0005'
% plot1(16),'DisplayName','039-02-0011'
% plot1(17),'DisplayName','039-02-0013'
% plot1(18),'DisplayName','039-13-0018'
% plot1(19),'DisplayName','039-02-0032'
% plot1(20),'DisplayName','039-02-0034'
% plot1(21),'DisplayName','039-02-0037'
% plot1(22),'DisplayName','039-09-0001'

% %FITS
 
% plot1(23),'DisplayName','039-02-0017'
% plot1(24),'DisplayName','039-02-0014'
% plot1(25),'DisplayName','039-13-0013'
% plot1(26),'DisplayName','039-13-0015'
% plot1(27),'DisplayName','039-13-0033'
% plot1(28),'DisplayName','039-13-0062'       
% plot1(29),'DisplayName','039-13-0037'
% plot1(30),'DisplayName','039-13-0038'
% plot1(31),'DisplayName','039-13-0060'
% plot1(32),'DisplayName','039-13-0103'
% plot1(33),'DisplayName','039-02-0030'
% plot1(34),'DisplayName','039-02-0031'
% plot1(35),'DisplayName','039-02-0033'
% plot1(36),'DisplayName','039-02-0036' 
% plot1(37),'DisplayName','039-02-0005'
% plot1(38),'DisplayName','039-02-0011'
% plot1(39),'DisplayName','039-02-0013'
% plot1(40),'DisplayName','039-13-0018'
% plot1(41),'DisplayName','039-02-0032'
% plot1(42),'DisplayName','039-02-0034'
% plot1(43),'DisplayName','039-02-0037'
% plot1(44),'DisplayName','039-09-0001'


%%%Excluding 02-0036, 02-0037 which did not neutralize matching virus

%%%%ORDER OF SAMPLES IN PLOT1 AND PLOT2
%SET 1
%  %POINTS
% plot1(1),'DisplayName','039-02-0017'
% plot1(2),'DisplayName','039-02-0014'
% plot1(3),'DisplayName','039-13-0013'
% plot1(4),'DisplayName','039-13-0015'
% plot1(5),'DisplayName','039-13-0033'
% plot1(6),'DisplayName','039-13-0062'       
% plot1(7),'DisplayName','039-13-0037'
% plot1(8),'DisplayName','039-13-0038'
% plot1(9),'DisplayName','039-13-0060'
% plot1(10),'DisplayName','039-13-0103'
% plot1(11),'DisplayName','039-02-0030'
% plot1(12),'DisplayName','039-02-0031'
% plot1(13),'DisplayName','039-02-0033'
% plot1(14),'DisplayName','039-02-0005'
% plot1(15),'DisplayName','039-02-0011'
% plot1(16),'DisplayName','039-02-0013'
% plot1(17),'DisplayName','039-13-0018'
% plot1(18),'DisplayName','039-02-0032'
% plot1(19),'DisplayName','039-02-0034'
% plot1(20),'DisplayName','039-09-0001'

% %FITS
 
% plot1(21),'DisplayName','039-02-0017'
% plot1(22),'DisplayName','039-02-0014'
% plot1(23),'DisplayName','039-13-0013'
% plot1(24),'DisplayName','039-13-0015'
% plot1(25),'DisplayName','039-13-0033'
% plot1(26),'DisplayName','039-13-0062'       
% plot1(27),'DisplayName','039-13-0037'
% plot1(28),'DisplayName','039-13-0038'
% plot1(29),'DisplayName','039-13-0060'
% plot1(30),'DisplayName','039-13-0103'
% plot1(31),'DisplayName','039-02-0030'
% plot1(32),'DisplayName','039-02-0031'
% plot1(33),'DisplayName','039-02-0033'
% plot1(34),'DisplayName','039-02-0005'
% plot1(35),'DisplayName','039-02-0011'
% plot1(36),'DisplayName','039-02-0013'
% plot1(37),'DisplayName','039-13-0018'
% plot1(38),'DisplayName','039-02-0032'
% plot1(39),'DisplayName','039-02-0034'
% plot1(40),'DisplayName','039-09-0001'
                    
            
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% WT (early variant) Include 484
            
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


 % Create figure
    figure3 = figure;

    axes3 = axes('Parent',figure3, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes3,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    plotSetToUse =[1:10, 11:13, 15:20, 22];
    
    for index = 1:20
        
        plotToUse = plotSetToUse(index);
    
        plot3(index) = errorbar(xAxis, meanFracWtCombinedSet(:,plotToUse).*100, stdFracWtCombinedSet(:,index).*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#d95f02');
                
                
    end
    
  
hold on
 

%%%%%%FITTING
%%%%do not fit A2051 (first) or PUI (last column)

IC50VectWtNout = [];

confIntervalsMatrixWtNout = [];

RsqVectWtNout= [];

for fitPlot =1:20 
    
    plotToUse = plotSetToUse(fitPlot);


[xData, yData] = prepareCurveData(xAxis, meanWtCombinedSet(:,plotToUse));

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50 = coeffvalues(fitresult);

confIntervals = confint(fitresult);

Rsq = gof.rsquare;

IC50VectWtNout = [IC50VectWtNout,IC50];

confIntervalsMatrixWtNout = [confIntervalsMatrixWtNout,confIntervals];

RsqVectWtNout= [RsqVectWtNout,Rsq];


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50));

hold on

%%%fitPlot-1 since index used to read out matrix, and A2015 in first
   %%%column excluded

plot3(20+fitPlot)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#d95f02'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

end



hold on


%%%%CHANGE COLORS FOR POINTS AND FITS ACCORDING TO SAMPLE (EG PID 103
%%%%GREEN) WHICH ARE DIFFERENT FROM MAIN SAMPLE (ORANGE, FIRST WAVE PLASMA,
%%%%NO MUTATIONS)

%POINTS

set(plot3(10),'MarkerFaceColor','#1b9e77');
set(plot3(11),'MarkerFaceColor','#7570b3');
set(plot3(12),'MarkerFaceColor','#7570b3');
set(plot3(13),'MarkerFaceColor','#7570b3');
set(plot3(18),'MarkerFaceColor','#7570b3');
set(plot3(19),'MarkerFaceColor','#7570b3');
set(plot3(20),'MarkerFaceColor','#7570b3');

%FITS

set(plot3(30),'Color','#1b9e77');
set(plot3(31),'Color','#7570b3');
set(plot3(32),'Color','#7570b3');
set(plot3(33),'Color','#7570b3');
set(plot3(38),'Color','#7570b3');
set(plot3(39),'Color','#7570b3');
set(plot3(40),'Color','#7570b3');

set(plot3(10),'DisplayName','E484K only plasma');
set(plot3(9),'DisplayName','First wave plasma');
set(plot3(1),'DisplayName','Second wave plasma');




saveas(gcf,'allDataWTnoOut.TIF','tif');

%% MT (501Y.V2 variant) include 484
            
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 % Create figure
    figure4 = figure;

    axes4 = axes('Parent',figure4, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes4,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    plotSetToUse =[1:10, 11:13, 15:20, 22];
    
    for index = 1:20
        
        plotToUse = plotSetToUse(index);
    
        plot4(index) = errorbar(xAxis, meanFracMtCombinedSet(:,plotToUse).*100, stdFracMtCombinedSet(:,index).*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#d95f02');
                
                
    end
    
  
hold on
 

%%%%%%FITTING
%%%%do not fit A2051 (first) or PUI (last column)

IC50VectMtNout = [];

confIntervalsMatrixMtNout = [];

RsqVectMtNout= [];

for fitPlot =1:20 
    
    plotToUse = plotSetToUse(fitPlot);


[xData, yData] = prepareCurveData(xAxis, meanMtCombinedSet(:,plotToUse));

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50 = coeffvalues(fitresult);

confIntervals = confint(fitresult);

Rsq = gof.rsquare;

IC50VectMtNout = [IC50VectMtNout,IC50];

confIntervalsMatrixMtNout = [confIntervalsMatrixMtNout,confIntervals];

RsqVectMtNout= [RsqVectMtNout,Rsq];


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50));

hold on

%%%fitPlot-1 since index used to read out matrix, and A2015 in first
   %%%column excluded

plot4(20+fitPlot)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#d95f02'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

end



hold on


%%%%CHANGE COLORS FOR POINTS AND FITS ACCORDING TO SAMPLE (EG PID 103
%%%%GREEN) WHICH ARE DIFFERENT FROM MAIN SAMPLE (ORANGE, FIRST WAVE PLASMA,
%%%%NO MUTATIONS)


%POINTS

set(plot4(10),'MarkerFaceColor','#1b9e77');
set(plot4(11),'MarkerFaceColor','#7570b3');
set(plot4(12),'MarkerFaceColor','#7570b3');
set(plot4(13),'MarkerFaceColor','#7570b3');
set(plot4(18),'MarkerFaceColor','#7570b3');
set(plot4(19),'MarkerFaceColor','#7570b3');
set(plot4(20),'MarkerFaceColor','#7570b3');

%FITS

set(plot4(30),'Color','#1b9e77');
set(plot4(31),'Color','#7570b3');
set(plot4(32),'Color','#7570b3');
set(plot4(33),'Color','#7570b3');
set(plot4(38),'Color','#7570b3');
set(plot4(39),'Color','#7570b3');
set(plot4(40),'Color','#7570b3');

saveas(gcf,'allDataMTnoOut.TIF','tif');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A2051 and PUI (PUI= Plasma from uninfected participants) WT

% Create figure
    figure7 = figure;

    axes7 = axes('Parent',figure7, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes7,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    xAxis = [0.04; 0.02; 0.01; 0.01/2; 0.01/4; 0.01/8; 0.01/16];
    
 
 
 plot7(1) = errorbar(xAxis, meanFracNeutPuiNoZeroWt.*100, stdFracNeutPuiWt.*100,'LineStyle', '--',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#bababa');
         
       hold on



   xAxisA2051 = [50 50/2 50/4 50/8 50/16 50/32 50/64];
                
                
% %ax1 = gca; % current axes
ax3_pos = axes7.Position; % position of first axes
ax4 = axes('Position',ax3_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none', 'FontSize',14);%,...
    

pbaspect([1 1 1])

hold(ax4,'on');

  plot7(2) = errorbar(xAxisA2051, meanFracNeutA2051NoZeroWt.*100, stdFracNeutA2051Wt.*100,'Parent',ax4,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#ca0020');
         
         %plot3(1) = errorbar(xAxisA2051, meanFracNeutA2051NoZeroWt.*100, stdFracNeutA2051Wt.*100,'LineStyle', 'none',...
           %  'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor',[0, 0, 0]);


  
hold on
 
%%%%%%FITTING



[xData, yData] = prepareCurveData(xAxisA2051, meanA2051Wt);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50A2051wt = coeffvalues(fitresult);

confIntervalsA2051wt = confint(fitresult);

RsqA2051wt = gof.rsquare;


xAxisFit = min(xAxisA2051):1:max(xAxisA2051);

TxFit = 1./(1+(xAxisFit./IC50A2051wt));

hold on

%%%fitPlot-1 since index used to read out matrix, and A2015 in first
   %%%column excluded

plot7(3)= plot(xAxisFit, (1-TxFit).*100, 'Parent',ax4, 'LineWidth', 1,'Color', '#ca0020'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

%plot1(30)= plot(xAxisFit, (1-TxFit).*100,'Parent',ax2, 'LineWidth', 1,'Color', [0 0 0]); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

set(gca,'XScale', 'log');
    set(gca,'xlim',[0.6 100]);
    set(gca,'ylim',[-10 110]);
    set(gca,'yticklabels',{'','','','','','',''});

%saveas(gcf,'WtSet1','tif');

saveas(gcf,'controlsWT.TIF','tif');


 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A2051 and PUI (PUI= Plasma from uninfected participants) MT

% Create figure
    figure8 = figure;

    axes8 = axes('Parent',figure8, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes8,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    xAxis = [0.04; 0.02; 0.01; 0.01/2; 0.01/4; 0.01/8; 0.01/16];
    
 
 
 plot8(1) = errorbar(xAxis, meanFracNeutPuiNoZeroMt.*100, stdFracNeutPuiMt.*100,'LineStyle', '--',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#bababa');
         
       hold on



   xAxisA2051 = [50 50/2 50/4 50/8 50/16 50/32 50/64];
                
                
% %ax1 = gca; % current axes
ax4_pos = axes8.Position; % position of first axes
ax5 = axes('Position',ax4_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none', 'FontSize',14);%,...
    

pbaspect([1 1 1])

hold(ax5,'on');

  plot8(2) = errorbar(xAxisA2051, meanFracNeutA2051NoZeroMt.*100, stdFracNeutA2051Mt.*100,'Parent',ax5,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#ca0020');
         
         %plot3(1) = errorbar(xAxisA2051, meanFracNeutA2051NoZeroWt.*100, stdFracNeutA2051Wt.*100,'LineStyle', 'none',...
           %  'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor',[0, 0, 0]);


  
hold on
 
%%%%%%FITTING



[xData, yData] = prepareCurveData(xAxisA2051, meanA2051Mt);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50A2051mt = coeffvalues(fitresult);

confIntervalsA2051mt = confint(fitresult);

RsqA2051mt = gof.rsquare;


xAxisFit = min(xAxisA2051):1:max(xAxisA2051);

TxFit = 1./(1+(xAxisFit./IC50A2051mt));

hold on

%%%fitPlot-1 since index used to read out matrix, and A2015 in first
   %%%column excluded

plot8(3)= plot(xAxisFit, (1-TxFit).*100 ,'Parent',ax5,'LineWidth', 1,'Color', '#ca0020'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

%plot1(30)= plot(xAxisFit, (1-TxFit).*100,'Parent',ax2, 'LineWidth', 1,'Color', [0 0 0]); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

set(gca,'XScale', 'log');
    set(gca,'xlim',[0.6 100]);
    set(gca,'ylim',[-10 110]);
    set(gca,'yticklabels',{'','','','','','',''});
    
    saveas(gcf,'controlsMT.TIF','tif');
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
%% COMBINED PIDS WT VIRUS: FIRST WAVE VS SECOND WAVE CHALLENGE

% Create figure
    figure9 = figure;

    axes9 = axes('Parent',figure9, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes9,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    
    
        plot9(1) = errorbar(xAxis, meanFracAllWtFWpl.*100, stdFracAllWtFWpl.*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#d95f02');
         
         plot9(2) = errorbar(xAxis, meanFracAllWtSWpl.*100, stdFracAllWtSWpl.*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#7570b3');
                

    
  
hold on
 

%%%%%%FITTING WT FW


[xData, yData] = prepareCurveData(xAxis, meanAllWtFWpl);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50CombWtFW = coeffvalues(fitresult);

confIntervalsCombWtFW = confint(fitresult);

RsqCombWtFW = gof.rsquare;


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50CombWtFW));


plot9(3)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#d95f02'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

hold on


%%%%%%FITTING WT SW


[xData, yData] = prepareCurveData(xAxis, meanAllWtSWpl);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50CombWtSW = coeffvalues(fitresult);

confIntervalsCombWtSW = confint(fitresult);

RsqCombWtSW = gof.rsquare;


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50CombWtSW));


plot9(4)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#7570b3'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

saveas(gcf,'combinedWT.TIF','tif');
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
%% COMBINED PIDS MT VIRUS: FIRST WAVE VS SECOND WAVE CHALLENGE

% Create figure
    figure10 = figure;

    axes10 = axes('Parent',figure10, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes10,'on');

    xlabel("Dilution")
    ylabel("% Neutralization")
    
    set(gca,'XScale', 'log');
                
    set(gca,'ylim',[-10 110]);

    set(gca,'xlim',[0.01/20 0.05]);

    hold on
    
    
    
        plot10(1) = errorbar(xAxis, meanFracAllMtFWpl.*100, stdFracAllMtFWpl.*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#d95f02');
         
         plot10(2) = errorbar(xAxis, meanFracAllMtSWpl.*100, stdFracAllMtSWpl.*100,'LineStyle', 'none',...
             'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#7570b3');
                

    
  
hold on
 

%%%%%%FITTING WT FW


[xData, yData] = prepareCurveData(xAxis, meanAllMtFWpl);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50CombMtFW = coeffvalues(fitresult);

confIntervalsCombMtFW = confint(fitresult);

RsqCombMtFW = gof.rsquare;


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50CombMtFW));


plot10(3)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#d95f02'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

hold on


%%%%%%FITTING WT SW


[xData, yData] = prepareCurveData(xAxis, meanAllMtSWpl);

ft = fittype( '1/(1+(x/a))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.964888535199277;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

IC50CombMtSW = coeffvalues(fitresult);

confIntervalsCombMtSW = confint(fitresult);

RsqCombMtSW = gof.rsquare;


xAxisFit = min(xAxis):0.0001:max(xAxis);

TxFit = 1./(1+(xAxisFit./IC50CombMtSW));


plot10(4)= plot(xAxisFit, (1-TxFit).*100, 'LineWidth', 1,'Color', '#7570b3'); %'Color', colormap(fitPlot, :), 'HandleVisibility','off')
%%%'HandleVisibility','off' takes it off legend

saveas(gcf,'combinedMT.TIF','tif');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PRNT50 line plot



NT50VectCombined =[1./IC50VectWtNout', 1./IC50VectMtNout']; %%%combine wt and mt

NT50VectCombinedFW =NT50VectCombined([1:10, 14:17],:);

NT50VectCombinedSW =NT50VectCombined([11:13, 18:20],:);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create figure
    figure11 = figure;

    axes11 = axes('Parent',figure11, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes11,'on');

    set(gca,'ylim',[log2(8) log2(2^13)]);

     set(gca,'xlim',[0.7 2.3]);

    hold on
    
    for pointSet= 1:numel(NT50VectCombinedFW(:,1))
  
        plot11(pointSet) = plot(1:2, log2(NT50VectCombinedFW(pointSet,:)),'LineStyle', '-',...
             'Color', '#d95f02', 'Marker', 'o', 'MarkerSize',8, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#d95f02');
         
%          plot6(2) = errorbar(xAxis, meanFracAllMtSWpl.*100, stdFracAllMtSWpl.*100,'LineStyle', 'none',...
%              'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#7570b3');
%                 
    end
    
    set(gca,'ytick', 3:13);
    
    set(gca,'XTick',zeros(1,0));
    
    set(gca,'xticklabels',{'','','',''});
    
    set(gca,'yticklabels',{'8','','32','','128','','512', '', '2048', '', '8192'});
    
    set(plot11(10),'MarkerFaceColor','#1b9e77', 'Color', '#1b9e77');
    
  
saveas(gcf,'connectPtsWT.TIF','tif');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create figure
    figure12 = figure;

    axes12 = axes('Parent',figure12, 'FontSize',14);%, 'FontWeight','bold'
    
    pbaspect([1 1 1])

     hold(axes12,'on');

%                 
    set(gca,'ylim',[log2(8) log2(2^13)]);

     set(gca,'xlim',[0.7 2.3]);

    hold on
    
    
    %%%remember n x 2 matrix
    
    NT50VectCombinedSWnoOut = NT50VectCombinedSW; %%%exclusion 02-0036 and 02-0037 already done
    
    for pointSet= 1:numel(NT50VectCombinedSWnoOut(:,1))
  
        plot12(pointSet) = plot(1:2, log2(NT50VectCombinedSWnoOut(pointSet,:)),'LineStyle', '-',...
             'Color', '#7570b3', 'Marker', 'o', 'MarkerSize',8, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#7570b3');
         
%          plot6(2) = errorbar(xAxis, meanFracAllMtSWpl.*100, stdFracAllMtSWpl.*100,'LineStyle', 'none',...
%              'Color', [0 0 0], 'Marker', 'o', 'MarkerSize',7, 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor','#7570b3');
%                 
    end
    
    set(gca,'ytick', 3:13);
    
    set(gca,'XTick',zeros(1,0));
    
    set(gca,'xticklabels',{'','','',''});
    
    set(gca,'yticklabels',{'8','','32','','128','','512', '', '2048', '', '8192'});
    
%     set(plot12(4),'MarkerFaceColor','#e7298a', 'Color', '#e7298a');
%     
%     set(plot12(7),'MarkerFaceColor','#e7298a', 'Color', '#e7298a');
    
  
saveas(gcf,'connectPtsSW.TIF','tif');


%%%%summary NT50 per FW and SW plasma

ratioNT50FWrange =NT50VectCombinedFW([1:9, 11:14],1)./NT50VectCombinedFW([1:9, 11:14],2) %%%exclude 484

ratioNT50SWrange =NT50VectCombinedSWnoOut(:,2)./NT50VectCombinedSWnoOut(:,1) %%%%EXCLUDE 0036 (INDEX 4) AND 0037 (INDEX 7) ON LIST OF SW PLASMA
    %%%remember n x 2 matrix, therefore noOut



maxFWrange=max(ratioNT50FWrange)

minFWrange=min(ratioNT50FWrange)

maxSWrange=max(ratioNT50SWrange)

minSWrange=min(ratioNT50SWrange)

geoMeanFWrange= geomean(ratioNT50FWrange)

geoMeanSWrange= geomean(ratioNT50SWrange)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



end

%% find fit to normal

if findGoF ==1
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%EXTRACT AND COMBINE DATA
    
    %%%%%NOTE DATA NORMALIZED BY NO PLASMA, THIS COLUMN DOES NOT APPEAR
    
    %%%%for GOF, exclude PUI and a2051 and make one long matrix combined
    %%%%across dilutions for multiplr participants. ie each column
    %%%%repeat
     
 cd(dirCombined);


     combMatrixWt1FW =[];
     combMatrixMt1FW =[];
     
     combMatrixWt2FW =[];
     combMatrixMt2FW =[];
 
     combMatrixWt2SW =[];
     combMatrixMt2SW =[];

     combMatrixWt3FW =[];
     combMatrixMt3FW =[];
     
     combMatrixWt3SW =[];
     combMatrixMt3SW =[];

 
 
 %%%%set 1: exp 1,2, 3 with same PIDS
 %%%%a2015 in column 1, PUI in column 8. Take out 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 for index=1:numel(experimentsSet1)
     
     expNum = experimentsSet1(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
           combMatrixWt1FW =[combMatrixWt1FW,matrixWt(:,2:7)];
           
           combMatrixMt1FW =[combMatrixMt1FW,matrixMt(:,2:7)];
           
     
 end

 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%set 2: exp 4,5,6,7 with same PIDS. a2015 in column 1, PUI in column 10, 02-0036 in column 9, 13-0103 in column 5. Take out 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%NOTE 4 experiments for this one!
  for index=1:numel(experimentsSet2)
     
     expNum = experimentsSet2(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
           combMatrixWt2FW =[combMatrixWt2FW,matrixWt(:,2:4)];
           combMatrixWt2SW =[combMatrixWt2SW,matrixWt(:,6:8)];
           
           combMatrixMt2FW =[combMatrixMt2FW,matrixMt(:,2:4)];
           combMatrixMt2SW =[combMatrixMt2SW,matrixMt(:,6:8)];
 end
 
 

%%%THIRD SET
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%set 3: exp 8,9,10 with same PIDS a2015 in column 1, PUI in column 10, 02-0037 in column 8. Take out 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  for index=1:numel(experimentsSet3)
     
     expNum = experimentsSet3(index);
     
     nameDataFile =  (['resultsFFUexp' num2str(expNum)]);
           
           load(nameDataFile);
           
          combMatrixWt3FW =[combMatrixWt3FW,matrixWt(:,2:5)];
          combMatrixWt3SW =[combMatrixWt3SW,matrixWt(:,[6,7,9])];
           
           combMatrixMt3FW =[combMatrixMt3FW,matrixMt(:,2:5)];
          combMatrixMt3SW =[combMatrixMt3SW,matrixMt(:,[6,7,9])];
  end

%%% COMBINE ALL DATASETS BY ROWS (dilutions)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



gofMatrixWTFW = [combMatrixWt1FW, combMatrixWt2FW, combMatrixWt3FW];
gofMatrixMTFW = [combMatrixMt1FW, combMatrixMt2FW, combMatrixMt3FW];

gofMatrixWTSW = [combMatrixWt2SW, combMatrixWt3SW];
gofMatrixMTSW = [combMatrixMt2SW, combMatrixMt3SW];



 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
 %%%FW
    for graphProb =1:7
    % Create figure
    
        if useWt ==1
        nameFigNorm = (['wtFWDil' num2str(graphProb)]);

        else

        nameFigNorm = (['mtFWDil' num2str(graphProb)]);

        end
        figure1 = figure;
        
%         % Create ylabel
%     ylabel('Probability','FontSize',18);
% 
%      % Create xlabel
%       xlabel('Data','FontSize',18);

        axes1 = axes('Parent',figure1);
        
        
         hold(axes1,'on');
         
          
                 
         if useWt ==1

          a = gofMatrixWTFW(graphProb, :);

         else

          a = gofMatrixMTFW(graphProb, :);

         end   
        h= normplot(a);
         
        h(2).LineWidth = 2; 
        h(1).MarkerSize = 10;
        
        set(gca,'FontSize',16);
        
        saveas(gcf,nameFigNorm,'jpg');
        
    end
        
       
 %%%SW
       
  for graphProb =1:7
    % Create figure
    
        if useWt ==1
        nameFigNorm = (['wtSWDil' num2str(graphProb)]);

        else

        nameFigNorm = (['mtSWDil' num2str(graphProb)]);

        end
        figure1 = figure;
        
%         % Create ylabel
%     ylabel('Probability','FontSize',18);
% 
%      % Create xlabel
%       xlabel('Data','FontSize',18);

        axes1 = axes('Parent',figure1);
        
        
         hold(axes1,'on');
         
          
                 
         if useWt ==1

          a = gofMatrixWTSW(graphProb, :);

         else

          a = gofMatrixMTSW(graphProb, :);

         end   
        h= normplot(a);
         
        h(2).LineWidth = 2; 
        h(1).MarkerSize = 10;
        
        set(gca,'FontSize',16);
        
        saveas(gcf,nameFigNorm,'jpg');
        
    end
    
  end













